## overall config file for first set of experiments stool sample dataset

dataset_dir: "comparisons/"
qiime_env: "qiime2-2023.5"

## --GLOBAL OPTIONS--
## are you starting with raw 16S sequences?
raw_sequences: "yes" ## options: yes and no 

## IF YOU HAVE SAID YES TO raw_sequences WHATEVER YOU PUT IN run_demux_only AND run_dada2_only WILL NOT MATTER
## option to split demux and dada2 steps so you can know where to trim/truncate your seqs
run_demux_only: "yes" ## options: yes and no
run_dada2_only: "yes" ## options: yes and no

## do you want to run taxonomic classification? chances are yes since you're running this workflow
tax_class: "no" ## options: yes and no, default is yes 

## do you want to run core metrics analysis on your data to get alpha/beta diversity?
core_metrics: "no" ## options: yes and no
## -------------------

## --NEEDED FILE PATHS--
## include if raw_sequences = "yes"
raw_seq_dir: "data/first_set_qiime/"
raw_seqs: ["SEQ016/oldExp_s3-016", "SEQ021/oldExp_s4-021", "SEQ024/oldExp_s5-024"]
dada2_trim_left_for: 13
dada2_trim_left_rev: 13
dada2_trunc_len_for: 230
dada2_trunc_len_rev: 160

## include if tax_class = "yes"
## if you ran raw sequences, you don't need to provide file paths for your biom_table and rep_seqs
## if not, you need to tell snakemake the file path to your biom_table and rep_seqs
biom_table: NA
rep_seqs: NA
metadata: NA

## include if core_metrics = "yes"
## what sampling depth do you want to use for your core metrics analysis? 
## if you're not sure, I'd consult data/qiime/taxonomy_filtered.qzv
core_metrics_sampling_depth: 0
## -------------------
